### ISSUE TITLE
Transactions "Confirmed" flag

### ISSUE THREAD

**Issue by karek314** [LiskHQ/lisk-explorer#97] opened 2017-03-14 17:39 UTC
Instead incrementing "X Confirmations" value in all transactions. There should be flag "Confirmed" upon some constant which can be that transaction has been confirmed by network. Let's say 300.

**Comment by 4miners** [comment] 2017-03-14 17:55
Transaction is confirmed by the network when it's included in block. Hovewer, node can rollback max 2 invalid blocks, so 3-5 confirmations should be enough to treat transaction as "confirmed", and "super-well-confirmed" after one round. Mark transactions as `Confirmed` after X confirmations may cause users to think that transactions below X confirmations are not confirmed - which is wrong. But maybe flag "Well confirmed" after 101 confirmations will be fine - but can lead to same issue as described above.

I leave issue open for discussion.

**Comment by karek314** [comment] 2017-03-14 18:37
I would say that it can display confirmations number up to 100-300. Then it simply can become "Confirmed" as iterating further makes no sense. This is something done in top bitcoin explorers. Even blocks are very well confirmed after 3-6 blocks.

Anyway, "help wanted" is a joke, right ? I'm not seeing any question in my message nor asking for help.

**Comment by 4miners** [comment] 2017-03-14 19:39
I added `help wanted` label because I want feedback from others, sorry if it's misleading.

**Comment by karek314** [comment] 2017-03-14 19:41
If there are custom labels available, there could be something like **discussion** but not sure if it's available.

**Comment by karek314** [comment] 2017-04-08 11:51
Why closed ? What is purpose of displaying thousands of confirmations ?

**Comment by karmacoma** [comment] 2017-04-08 12:01
@karek314 My mistake actually, it's not because we like winding you up, I promise ;)

Anyway, we will take a second look. Adding to next milestone. You are right from point of view of making "confirmation" state easier to understand. Thank you.

**Comment by Isabello** [comment] 2017-05-22 09:40
Closed via #154

**Closed by Isabello** 2017-05-22 09:40 UTC
Labels: enhancement
