### ISSUE TITLE
Network Monitor: version column does not sort numerically

### ISSUE THREAD

**Issue by Nazgolze** [LiskHQ/lisk-explorer#451] opened 2018-03-01 12:59 UTC
### Expected behaviour
Version column should sort numerically
### Actual behaviour
It seems to be a typical string sort. So ascending sort shows 0.10.0 as being less than 0.9.9 because 1 comes before 9 in the ascii chart
### Steps to reproduce
It's most visible in mainnet - https://explorer.lisk.io/networkMonitor
1. Go to the network monitor page
2. Scroll down and click the version column header so it gets the little up arrow

**Comment by karmacoma** [comment] 2018-03-06 13:42
Duplicate of: #449

**Closed by karmacoma** 2018-03-06 13:42 UTC
Labels: bug, duplicate
